name: Main pipeline

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.1'
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          composer install -q --no-ansi \
          --no-interaction --no-scripts --no-progress
      - name: PHP Stan
        run: ./vendor/bin/phpstan analyse -l 9 --memory-limit=1G ./src
      - name: PHP insights
        run: ./vendor/bin/phpinsights analyse ./src
      - name: Run Test
        run: ./vendor/bin/phpunit ./tests/